name: experiment-ci-cd
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Espressif IoT Development Framework (ESP-IDF)
        uses: espressif/esp-idf-ci-action@v1.1.0
        with:
          esp_idf_version: v4.4
          target: esp32
      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: experiment-ci-cd
          path: build/experiment-ci-cd.bin

  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    needs: [build]
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Build tests
        run: |
          sudo apt-get install libcriterion-dev
          sudo apt-get install meson
          cd test
          gcc -o test test.c -lcriterion
          ./test --xml > test.xml
      - name: Show results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test/test.xml

  delivery:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [test]
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: experiment-ci-cd
      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "experiment-ci-cd.bin"
          tag: 8.1.5
          bodyFile: "body.md"